---
- hosts: localhost
  gather_facts: no
  roles:
  - role: application_metrics
    monitoring_namespace: openshift-application-metrics
    namespace_postfix: -{{ monitoring_namespace }}
    monitoring_display_name: Application Metrics
    when: application_metrics | default(true) | bool